# Generated by Django 2.2.16 on 2020-09-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='customtext',
            name='dinolasers',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='dinolasers',
            field=models.TextField(blank=True),
        ),
    ]
